apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nsp-prod
resources:
  - ../../base
replicas:
  - name: orders-api
    count: 2
images:
  - name: orders-api
    newName: crnspcoredev8l2m0.azurecr.io/orders-api
    digest: sha256:f457b29393012213eaf501c32a6e4f58f9eea707e8e7001c7c4014ce081e03bf
