apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nsp-prod
resources:
  - ../../base
replicas:
  - name: orders-api
    count: 2
images:
  - name: orders-api
    newName: crnspcoredev8l2m0.azurecr.io/orders-api
    digest: sha256:7d63cc6a3cca3df39b805f440e7d60b19ab5477ad3f64a4763bbeea955552754
