apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-orders
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "77dacc0e-1cd0-4c40-89a6-e55d6ff64a39"
    keyvaultName: "kv-nsp-plat-dev-8l2m0"
    tenantId: "e273d616-402c-4fdf-a5e3-a03921a0fd51"
    objects: |
      array:
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: db-host
          objectType: secret
